version: "3"
services:
  bitcoind:
    build: bhartford419_loc/bitkernd
    ports:
     - "8332:8332"
     - "8333:8333"
    volumes:
     - /home/dock_v1/bitcoin_data:/bitcoin/data 
     - /home/dock_v1/bitcoin/bitcoin.conf:/bitcoin/bitcoin.conf
